export { default as Homepage } from './Homepage'
export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as ErrorPage } from './ErrorPage'
export { default as TrackParcel } from './TrackParcel'
export { default as Login } from './Login'
export { default as Register } from './Register'
